
export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL='USER_SIGNIN_FAIL'

export const USER_SIGNUP_REQUEST='USER_SIGNIN_REQUEST'
export const USER_SIGNUP_SUCCESS='USER_SIGNIN_SUCCESS'
export const USER_SIGNUP_FAIL='USER_SIGNIN_FAIL'


export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_USER_GROUP_SUCCESS = 'GET_USER_GROUP_SUCCESS'
export const GET_USER_GROUP_FAIL = 'GET_USER_GROUP_FAIL'

export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS'
export const GET_GROUP_MEMBERS_FAIL = 'GET_GROUP_MEMBERS_FAIL'